services:
  nginx:
    depends_on:
    - web
    environment:
      SERVICE_80_NAME: nginx
    env_file:
      - _local_deploy/common.env
      - .env
    restart: on-failure
    image: nginx:1.21
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    ports:
    - 443:443
    - 80:80
    volumes_from:
    - service:web:ro
    volumes:
    - ./_local_deploy/nginx.conf:/etc/nginx/conf.d/web.template:ro

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
    - postgresdb
    env_file:
      - _local_deploy/common.env
      - .env
    environment:
      SERVICE_8000_NAME: web
    user: root
    networks:
      - default

  postgresdb:
    container_name: postgresdb
    environment:
      SERVICE_5432_NAME: postgresdb
      POSTGRES_DB: film_todo
      POSTGRES_USER: film_todo
      POSTGRES_PASSWORD: hg6cn0i8QqcrfHWWwldYgkgv8U8K
    image: postgres:13-alpine
    volumes:
    - psgrdata:/var/lib/postgresql/data:rw
    networks:
      - default

volumes:
  psgrdata: {}

networks:
  default: {}
