# Generated by Django 4.1.3 on 2022-11-20 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kinopoisk', models.IntegerField(unique=True)),
                ('type', models.CharField(blank=True, choices=[('movie', 'Movie'), ('tv-series', 'Series'), ('cartoon', 'Cartoon'), ('anime', 'Anime')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('title_alternative', models.CharField(max_length=200)),
                ('poster', models.URLField(max_length=400)),
                ('directors', models.JSONField(default=[])),
                ('actors', models.JSONField(default=[])),
                ('genres', models.JSONField(default=[])),
                ('countries', models.JSONField(default=[])),
                ('year', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('tagline', models.CharField(max_length=300)),
                ('age_rating', models.IntegerField(null=True)),
                ('budget', models.IntegerField(null=True)),
                ('rating_kinopoisk', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('kinopoisk_votes', models.IntegerField(null=True)),
                ('rating_imdb', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('imdb_votes', models.IntegerField(null=True)),
                ('fees_world', models.IntegerField(null=True)),
                ('fees_russia', models.IntegerField(null=True)),
                ('premiere_world', models.DateField(blank=True, null=True)),
                ('premiere_russia', models.DateField(blank=True, null=True)),
                ('frames', models.JSONField(default=[])),
                ('screenshots', models.JSONField(default=[])),
                ('seasons', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('is_viewed', models.BooleanField(default=False)),
                ('user_rating', models.PositiveIntegerField(default=0)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todo.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
