# Generated by Django 4.1.3 on 2022-12-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_generate_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors_photos',
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_russia',
            field=models.IntegerField(null=True, verbose_name='Fees Russia'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_world',
            field=models.IntegerField(null=True, verbose_name='Fees World'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere_russia',
            field=models.DateField(blank=True, null=True, verbose_name='Premiere Russia'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere_world',
            field=models.DateField(blank=True, null=True, verbose_name='Premiere World'),
        ),
    ]
