# Generated by Django 4.1.3 on 2023-01-27 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_generate_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='fees_russia',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='fees_world',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='frames',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='screenshots',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='seasons',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tagline',
        ),
        migrations.AddField(
            model_name='movie',
            name='slogan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='watchability',
            field=models.JSONField(default=[], null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere_russia',
            field=models.DateField(blank=True, null=True, verbose_name='Premiere Russia'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere_world',
            field=models.DateField(blank=True, null=True, verbose_name='Premiere World'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_alternative',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.movie'),
        ),
    ]
