# Generated by Django 4.1.3 on 2023-01-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('todo', '0003_remove_movie_actors_photos_alter_movie_fees_russia_and_more'), ('todo', '0004_alter_note_movie')]

    dependencies = [
        ('todo', '0002_generate_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors_photos',
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_russia',
            field=models.IntegerField(null=True, verbose_name='Fees Russia'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_world',
            field=models.IntegerField(null=True, verbose_name='Fees World'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere_russia',
            field=models.DateField(blank=True, null=True, verbose_name='Premiere Russia'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere_world',
            field=models.DateField(blank=True, null=True, verbose_name='Premiere World'),
        ),
        migrations.AlterField(
            model_name='note',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='todo.movie'),
        ),
    ]
