# Generated by Django 4.1.3 on 2023-01-07 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_movie_actors_photos_alter_movie_fees_russia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='todo.movie'),
        ),
    ]
