# Generated by Django 4.1.3 on 2023-01-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_movie_actors_photos_alter_movie_fees_russia_and_more_squashed_0004_alter_note_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tagline',
            new_name='slogan',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='frames',
            new_name='watchability',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='fees_russia',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='fees_world',
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
