# Generated by Django 4.1.3 on 2023-01-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_tagline_movie_slogan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='screenshots',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='seasons',
        ),
    ]
