# Generated by Django 4.1.3 on 2023-01-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_movie_screenshots_remove_movie_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title_alternative',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
