# Generated by Django 4.1.3 on 2023-01-27 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_movie_description_alter_movie_slogan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.movie'),
        ),
    ]
