# Generated by Django 4.1.3 on 2023-01-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_note_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='watchability',
            field=models.JSONField(default=[], null=True),
        ),
    ]
